#!/bin/bash

cd "${0%/*}"

if [ -f config.conf ]; then
    . config.conf
fi

python3 run.py -host "$HOST" -port "$PORT" -client_id "$CLIENT_ID" -client_secret "$CLIENT_SECRET" -audio_file "$AUDIO_FILE"